let
    Source = Csv.Document(File.Contents("C:\Prima\Data_Analytics-Projects\Data_Analytics-Projects\Mental Health in Tech Workplace Analysis [Excel-mySQL-Power BI-Python]\Data\mental_health_raw.csv"),[Delimiter=",", Columns=27, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Change Age Data Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Timestamp", type datetime}, {"Age", Int64.Type}}),
    #"Select Age" = Table.SelectRows(#"Change Age Data Type", each [Age] >= 18 and [Age] <= 65),
    #"Add Gender Revised Column" = Table.AddColumn(#"Select Age", "Gender_Revised", each if [Gender] = "Male " then "Male" else if [Gender] = "m" then "Male" else if [Gender] = "M" then "Male" else if [Gender] = "Mail" then "Male" else if [Gender] = "maile" then "Male" else if [Gender] = "Make" then "Male" else if [Gender] = "Mal" then "Male" else if [Gender] = "male" then "Male" else if [Gender] = "Man" then "Male" else if [Gender] = "msle" then "Male" else if [Gender] = "Cis Male" then "Male" else if [Gender] = "cis male" then "Male" else if [Gender] = "Male (CIS)" then "Male" else if [Gender] = "male learning androgynous" then "Male" else if [Gender] = "Male-ish" then "Male" else if [Gender] = "something kinda male?" then "Male" else if [Gender] = "Female " then "Female" else if [Gender] = "f" then "Female" else if [Gender] = "F" then "Female" else if [Gender] = "Femake" then "Female" else if [Gender] = "female" then "Female" else if [Gender] = "Cis Female" then "Female" else if [Gender] = "cis-female/femme" then "Female" else if [Gender] = "woman" then "Female" else if [Gender] = "Woman" then "Female" else if [Gender] = "Female (cis)" then "Female" else if [Gender] = "Male" then "Male" else if [Gender] = "Female" then "Female" else "Other"),
    #"Reordered Columns" = Table.ReorderColumns(#"Add Gender Revised Column",{"Timestamp", "Age", "Gender", "Gender_Revised", "Country", "state", "self_employed", "family_history", "treatment", "work_interfere", "no_employees", "remote_work", "tech_company", "benefits", "care_options", "wellness_program", "seek_help", "anonymity", "leave", "mental_health_consequence", "phys_health_consequence", "coworkers", "supervisor", "mental_health_interview", "phys_health_interview", "mental_vs_physical", "obs_consequence", "comments"}),
    #"Change Gender_Revised Data Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"Gender_Revised", type text}}),
    #"""NA"" to null on self_employed column" = Table.ReplaceValue(#"Change Gender_Revised Data Type","NA","",Replacer.ReplaceText,{"self_employed"}),
    #"""NA"" to null on work_interfere column" = Table.ReplaceValue(#"""NA"" to null on self_employed column","NA","",Replacer.ReplaceText,{"work_interfere"}),
    #"""NA"" to null on comments column" = Table.ReplaceValue(#"""NA"" to null on work_interfere column","NA","",Replacer.ReplaceText,{"comments"}),
    #"Removed Gender Columns" = Table.RemoveColumns(#"""NA"" to null on comments column",{"Gender"}),
    #"Renamed ""Gender_Revised"" into ""Gender""" = Table.RenameColumns(#"Removed Gender Columns",{{"Gender_Revised", "Gender"}}),
    #"Inserted Replaced Text" = Table.AddColumn(#"Renamed ""Gender_Revised"" into ""Gender""", "Replaced Text", each Text.Replace([no_employees], "-", " - "), type text),
    #"Reordered Columns1" = Table.ReorderColumns(#"Inserted Replaced Text",{"Timestamp", "Age", "Gender", "Country", "state", "self_employed", "family_history", "treatment", "work_interfere", "no_employees", "Replaced Text", "remote_work", "tech_company", "benefits", "care_options", "wellness_program", "seek_help", "anonymity", "leave", "mental_health_consequence", "phys_health_consequence", "coworkers", "supervisor", "mental_health_interview", "phys_health_interview", "mental_vs_physical", "obs_consequence", "comments"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns1",{"no_employees"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Replaced Text", "no_employees"}})
in
    #"Renamed Columns"